driver:
  type: qemu
  image: ubuntu/18.04
sources:
  - url: https://github.com/andrewpillar/jrnl
stages:
  - configure
  - build
  - test
jobs:
  - stage: configure
    commands:
      - apt-get install gcc -y
      - wget https://dl.google.com/go/go1.11.linux-amd64.tar.gz
      - tar -xf go1.11.linux-amd64.tar.gz
      - mv go /usr/local
      - PATH="$PATH:/usr/local/go/bin"
      - go version
      - go env
  - stage: build
    commands:
      - PATH="$PATH:/usr/local/go/bin"
      - cd /root/jrnl
      - GO111MODULE=on go install
  - stage: test
    commands:
      - PATH="$PATH:/root/go/bin"
      - cd /root/jrnl
      - ./test.sh
    artifacts:
      - /root/go/bin/jrnl
